# Generated by Django 6.1.1 on 2026-09-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='preco_custo',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='preco_venda',
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='quantidade',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque_atual',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque_minimo',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
