# Generated by Django 6.1.1 on 2026-09-13 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_destino'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='estoque.destino'),
        ),
    ]
