# Generated by Django 6.1.1 on 2026-09-13 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_movimentacao_destino'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='capacidade_gb',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='codigo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='produto',
            name='condicao',
            field=models.CharField(blank=True, choices=[('NOVO', 'Novo'), ('USADO', 'Usado'), ('LACRADO', 'Lacrado')], max_length=20),
        ),
        migrations.AddField(
            model_name='produto',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produto',
            name='documento_origem',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='produto',
            name='imei',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='produto',
            name='origem',
            field=models.CharField(choices=[('CHINA', 'China'), ('INDIA', 'Índia'), ('NAO_INDICADO', 'Não indicado')], default='NAO_INDICADO', max_length=20),
        ),
        migrations.AddField(
            model_name='produto',
            name='pagina_origem',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='ram_gb',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='tipo_produto',
            field=models.CharField(choices=[('SMARTPHONE', 'Smartphone'), ('TABLET', 'Tablet'), ('NOTEBOOK', 'Notebook'), ('COMPUTADOR', 'Computador'), ('MONITOR', 'Monitor'), ('ACESSORIO', 'Acessório'), ('OUTRO', 'Outro')], default='OUTRO', max_length=30),
        ),
    ]
