# Generated by Django 6.1.1 on 2026-09-13 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_produto_capacidade_gb_produto_codigo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='capacidade_gb',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='destacado',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='imei',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='origem',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='pagina_origem',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='ram_gb',
        ),
    ]
