# Generated by Django 6.1.1 on 2026-09-13 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_remove_produto_capacidade_gb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='tipo_produto',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
