# Generated by Django 6.1.1 on 2026-09-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0007_alter_produto_tipo_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='tipo',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='produto',
            name='condicao',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
