# Generated by Django 6.1.1 on 2026-09-16 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0008_alter_movimentacao_tipo_alter_produto_condicao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True)),
                ('capacidade', models.CharField(blank=True, max_length=100)),
                ('memoria_ram', models.CharField(blank=True, max_length=100)),
                ('condicao', models.CharField(blank=True, max_length=20)),
                ('origem', models.CharField(blank=True, max_length=100)),
                ('documento_origem', models.CharField(blank=True, max_length=100)),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('observacao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configuracoes', to='estoque.produto')),
            ],
            options={
                'verbose_name': 'Configuração de estoque',
                'verbose_name_plural': 'Configurações de estoque',
                'ordering': ['produto__nome', 'capacidade', 'memoria_ram', 'condicao'],
            },
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='configuracao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='estoque.configuracaoestoque'),
        ),
    ]
