# Generated by Django 6.1.1 on 2026-09-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0010_zerar_estoque_inicial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracaoestoque',
            options={'ordering': ['produto__nome', 'marca', 'modelo', 'capacidade', 'memoria_ram', 'condicao'], 'verbose_name': 'Configuração de estoque', 'verbose_name_plural': 'Configurações de estoque'},
        ),
        migrations.AddField(
            model_name='configuracaoestoque',
            name='cor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='configuracaoestoque',
            name='dimensoes',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='configuracaoestoque',
            name='marca',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='configuracaoestoque',
            name='material',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='configuracaoestoque',
            name='modelo',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
